# Generated by Django 3.2.18 on 2023-03-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20230328_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
